# Environment Configuration for WorldInteract Framework
# Pipeline Flow: Scenario Collection → Tool Dependency Graph Modeling → Function Schema Programmatic Materialization

# =============================================================================
# PHASE 1: SCENARIO COLLECTION
# Raw API processing, cleaning, and standardization
# =============================================================================
scenario_collection:
  min_tool_name_length: 3
  max_tool_name_length: 50
  required_fields: ["name", "description", "parameters", "returns"]
  duplicate_threshold: 0.8  # Similarity threshold for detecting duplicates (ignored when similarity_method is "none")
  description_min_length: 10
  similarity_method: None  # Options:
                                         # - "embedding_model": Use OpenAI embeddings for semantic similarity (most accurate, requires API key)
                                         # - "sequence_matcher": Use text-based similarity (fast, no external dependencies)
                                         # - "none": Only remove exact function name duplicates (fastest)

# =============================================================================
# PHASE 2: TOOL DEPENDENCY GRAPH MODELING
# Domain clustering and dependency analysis
# =============================================================================
dependency_graph:
  similarity_threshold: 0.5  # Cosine similarity threshold for creating edges
  min_community_size: 2      # Minimum tools per domain
  max_community_size: 20     # Maximum tools per domain
  louvain_resolution: 1.0    # Louvain algorithm resolution parameter
  enable_llm_validation: true # Whether to use LLM for dependency validation
  handle_singleton: false    # Whether to handle singleton tools by assigning them to existing domains
  singleton_tool_similarity_threshold: 0.6  # Similarity threshold for singleton tools to join domains

# =============================================================================
# PHASE 3: FUNCTION SCHEMA PROGRAMMATIC MATERIALIZATION
# Database schema generation, tool implementation, and state initialization
# =============================================================================

# State generation settings
state_generation:
  min_records_per_table: 3  # Minimum number of records to generate per database table
  max_records_per_table: 5  # Maximum number of records to generate per database table

# Code agent settings (replaces tool generation + validation)
code_agent:
  test_case_num: 3  # Number of test cases to generate for each tool
  max_code_agent_rounds: 10  # Maximum number of code generation and validation rounds
  enable_sandbox: true  # Whether to enable sandboxed code execution for safety
  sandbox_timeout: 30  # Timeout in seconds for sandbox execution

# Domain-specific settings
# Suggested table names for each domain
domains:
  file_operations:
    schema_tables: ["files", "directories", "permissions", "metadata"]  # Suggested table names for file operations domain
  
  web_browsing:
    schema_tables: ["pages", "links", "cookies", "history", "bookmarks"]  # Suggested table names for web browsing domain
  
  database_management:
    schema_tables: ["databases", "tables", "indexes", "queries", "connections"]  # Suggested table names for database management domain

