# Model Configuration for WorldInteract Framework
# Pipeline Flow: Scenario Collection → Tool Domain Graph Modeling → Function Schema Programmatic Materialization

# =============================================================================
# PHASE 1: SCENARIO COLLECTION
# Raw API processing, cleaning, and standardization
# =============================================================================
scenario_collection:
  model: "openai_gpt"
  temperature: 1.0
  max_tokens: 8124
  retry_attempts: 3

# =============================================================================
# PHASE 2: TOOL DOMAIN GRAPH MODELING
# Domain clustering and domain analysis
# =============================================================================
domain_graph:
  model: "openai_gpt"
  temperature: 0.1
  max_tokens: 4096
  retry_attempts: 3

# =============================================================================
# PHASE 3: FUNCTION SCHEMA PROGRAMMATIC MATERIALIZATION
# Database schema generation, tool implementation, and state initialization
# =============================================================================

# Schema generation configuration
schema_generation:
  model: "claude_3d7"
  temperature: 1.0
  max_tokens: 8124
  retry_attempts: 3

# Tool implementation configuration
tool_generation:
  model: "claude_3d7"
  temperature: 1.0
  max_tokens: 12384
  retry_attempts: 3

# Initial state generation configuration
state_generation:
  model: "claude_3d7"
  temperature: 1.0
  max_tokens: 12384
  retry_attempts: 3

# =============================================================================
# QUALITY ASSURANCE AND TESTING
# Validation, testing, and quality control
# =============================================================================

# Tool validation configuration
validation:
  model: "claude_3d7"
  temperature: 1.0
  max_tokens: 8214
  retry_attempts: 3

# Test case generation configuration
test_generation:
  model: "claude_3d7"
  temperature: 1.0
  max_tokens: 8124
  retry_attempts: 3

# Validation agent configuration - REMOVED (functionality moved to code_agent)

# Code agent configuration (replaces tool generation + validation)
code_agent:
  model: "claude_3d7"
  temperature: 0.3
  max_tokens: 12288
  retry_attempts: 3

# =============================================================================
# PHASE 4: TASK GRAPH GENERATION AND TRAJECTORY SYNTHESIS
# Random walk generation and edge validation
# =============================================================================

# Edge validation configuration
# Validates matching_pairs between function outputs and inputs using LLM
edge_validation:
  model: "openai_gpt"
  temperature: 0.1
  max_tokens: 8124
  retry_attempts: 3

# =============================================================================
# EMBEDDING AND SIMILARITY MODELS
# Semantic analysis and similarity computation
# =============================================================================
embedding:
  model: "text-embedding-3-large"
  api_base: "https://api.openai.com/v1"
  dimensions: 3072
  batch_size: 100

# =============================================================================
# PHASE 5: TRAJECTORY GENERATION
# Generate complete interaction trajectories from random walks using ReAct agent
# =============================================================================
trajectory_generation:
  model: "claude_3d7"
  temperature: 0.7
  max_tokens: 8192
  retry_attempts: 3

# =============================================================================
# DEFAULT FALLBACK CONFIGURATION
# Used when task-specific configuration is not available
# =============================================================================
default:
  model: "claude_3d7"
  temperature: 1.0
  max_tokens: 8124
  retry_attempts: 3

