# Model Configuration for WorldInteract Framework
# Pipeline Flow: Scenario Collection → Tool Domain Graph Modeling → Function Schema Programmatic Materialization

# =============================================================================
# AVAILABLE MODEL OPTIONS
# =============================================================================
# You can use any of the following model names in the "model" field below.
# These names map to specific models from different providers via CAMEL.
#
# Anthropic Claude Series:
#   - claude_3d7          : Claude 3.7 Sonnet (latest)
#   - claude_sonnet_4     : Claude Sonnet 4
#   - claude_opus_4       : Claude Opus 4
#   - claude_opus_4_1     : Claude Opus 4.1
#   - claude_3_5_sonnet   : Claude 3.5 Sonnet
#   - claude_3_5_haiku    : Claude 3.5 Haiku
#   - claude_3_opus       : Claude 3 Opus
#   - claude_3_sonnet     : Claude 3 Sonnet
#   - claude_3_haiku      : Claude 3 Haiku
#
# OpenAI GPT Series:
#   - openai_gpt          : GPT-4o (default OpenAI model)
#   - gpt4o               : GPT-4o
#   - gpt4o_mini          : GPT-4o Mini
#   - gpt4_turbo          : GPT-4 Turbo
#   - gpt4                : GPT-4
#   - gpt3_5_turbo        : GPT-3.5 Turbo
#
# OpenAI O1 Series:
#   - o1                  : O1
#   - o1_mini             : O1 Mini
#   - o1_preview          : O1 Preview
#
# Google Gemini Series:
#   - gemini_2_5_pro      : Gemini 2.5 Pro
#   - gemini_2_5_flash    : Gemini 2.5 Flash
#   - gemini_2_0_flash    : Gemini 2.0 Flash (Experimental)
#   - gemini_1_5_pro      : Gemini 1.5 Pro
#   - gemini_1_5_flash    : Gemini 1.5 Flash
#
# =============================================================================

# =============================================================================
# PHASE 1: SCENARIO COLLECTION
# Raw API processing, cleaning, and standardization
# =============================================================================
scenario_collection:
  model: "gpt4o_mini"
  temperature: 1.0
  max_tokens: 8124
  retry_attempts: 3

# =============================================================================
# PHASE 2: TOOL DOMAIN GRAPH MODELING
# Domain clustering and domain analysis
# =============================================================================
domain_graph:
  model: "o1_mini"
  temperature: 1.0
  max_tokens: 12384
  retry_attempts: 3

# =============================================================================
# PHASE 3: FUNCTION SCHEMA PROGRAMMATIC MATERIALIZATION
# Database schema generation, tool implementation, and state initialization
# =============================================================================

# Schema generation configuration
schema_generation:
  model: "gpt4o"
  temperature: 0.4
  max_tokens: 12384
  retry_attempts: 3

# Tool implementation configuration
tool_generation:
  model: "gpt4o"
  temperature: 1.0
  max_tokens: 12384
  retry_attempts: 3

# Initial state generation configuration
state_generation:
  model: "gpt4o"
  temperature: 1.0
  max_tokens: 12384
  retry_attempts: 3

# Code agent configuration
code_agent:
  model: "claude_sonnet_4"
  temperature: 1.0
  max_tokens: 12384
  retry_attempts: 3
  extra_body:
    thinking:
      type: enabled
      budget_tokens: 4096

# Tool refinement configuration
# Refines generated tools for consistency across the tool suite
tool_refinement:
  model: "claude_sonnet_4"
  temperature: 1.0
  max_tokens: 32768
  retry_attempts: 2
  extra_body:
    thinking:
      type: enabled
      budget_tokens: 4096

# =============================================================================
# PHASE 4: TASK GRAPH GENERATION AND TRAJECTORY SYNTHESIS
# Random walk generation and edge validation
# =============================================================================

# Edge validation configuration
# Validates matching_pairs between function outputs and inputs using LLM
edge_validation:
  model: "gpt4o"
  temperature: 0.1
  max_tokens: 8124
  retry_attempts: 3

# =============================================================================
# EMBEDDING AND SIMILARITY MODELS
# Semantic analysis and similarity computation
# =============================================================================
embedding:
  model: "text-embedding-3-large"
  api_base: "https://api.openai.com/v1"
  dimensions: 3072
  batch_size: 100

# =============================================================================
# PHASE 5: TRAJECTORY GENERATION
# Generate complete interaction trajectories from random walks using ReAct agent
# =============================================================================
trajectory_generation:
  model: "claude_sonnet_4"
  temperature: 0.7
  max_tokens: 12288
  retry_attempts: 3

# =============================================================================
# DEFAULT FALLBACK CONFIGURATION
# Used when task-specific configuration is not available
# =============================================================================
default:
  model: "gpt4o_mini"
  temperature: 1.0
  max_tokens: 12288
  retry_attempts: 3

